site_name: otExperimentalMeasurement
repo_url: https://github.com/fpgmaas/otExperimentalMeasurement
site_url: https://fpgmaas.github.io/otExperimentalMeasurement
site_description: Collection of class to ease use of opentunrs applied to experimental measurements
site_author: Pascal Borel
edit_uri: edit/main/docs/
repo_name: fpgmaas/otExperimentalMeasurement
copyright: Maintained by <a href="https://fpgmaas.com">fpgmaas</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [otexperimentalmeasurement]
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/fpgmaas/otExperimentalMeasurement
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/otExperimentalMeasurement

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
